# Generated by Django 2.1.15 on 2020-11-27 01:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('navenodriza', '0003_auto_20201127_0057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aeronave',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('nombre', models.CharField(max_length=50)),
                ('max_marcianos', models.IntegerField()),
                ('destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destinonavenodriza', to='navenodriza.NaveNodriza')),
                ('origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origennavenodriza', to='navenodriza.NaveNodriza')),
            ],
        ),
    ]
