# Generated by Django 2.1.15 on 2020-12-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aeronave', '0005_historialnaverevisada'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialnaverevisada',
            name='identificador',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
