# Generated by Django 2.1.15 on 2020-11-27 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navenodriza', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navenodriza',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
