# Generated by Django 2.1.15 on 2020-11-27 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navenodriza', '0002_auto_20201127_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navenodriza',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
